name: Just test something

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
      env:
        required: false
        type: string
        default: dev
jobs:
  create-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
