name: Just test something
run-name: "Build with env: ${{ inputs.env }}, tag: ${{ inputs.tag }}, branch: ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for manual build'
        default: ''
        type: string
      env:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
jobs:
  create-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
